name: 'Test Feature Branch'

on:
  push:
    branches:
    - 'feature/**'

jobs:
  run-terraform-test:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: cross-account--dns-infrastructure

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan
